import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

export const generateJobReport = (job, logs, tasks, orders, tools, timeEntries, settings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  if (settings?.companyLogo) {
    try {
      doc.addImage(settings.companyLogo, 'PNG', 15, 10, 30, 30);
    } catch (e) {
      console.log('Could not add logo');
    }
  }
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(settings?.companyName || 'SiteMaster Diary', settings?.companyLogo ? 50 : 15, 25);
  
  doc.setFontSize(16);
  doc.text('Job Report', 15, 45);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${format(new Date(), 'PPpp')}`, 15, 52);

  // Job Details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Job Information', 15, 65);
  
  doc.autoTable({
    startY: 70,
    head: [['Field', 'Value']],
    body: [
      ['Job Name', job.name],
      ['Address', job.address],
      ['Client', job.client || 'N/A'],
      ['Status', job.status || 'Active'],
      ['Progress', `${job.progress || 0}%`],
      ['Start Date', job.startDate || 'N/A'],
      ['Expected End', job.expectedEndDate || 'N/A']
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] }
  });

  // Time Summary
  const totalHours = timeEntries
    .filter(te => te.jobId === job._id)
    .reduce((sum, te) => sum + (te.hours || 0), 0);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Time Summary', 15, doc.lastAutoTable.finalY + 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Total Hours Logged: ${totalHours.toFixed(1)} hours`, 15, doc.lastAutoTable.finalY + 25);

  // Tasks
  const jobTasks = tasks.filter(t => t.jobId === job._id);
  if (jobTasks.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Tasks', 15, 20);

    doc.autoTable({
      startY: 25,
      head: [['Title', 'Status', 'Priority', 'Due Date', 'Assigned To']],
      body: jobTasks.map(t => [
        t.title,
        t.status,
        t.priority,
        t.dueDate || 'N/A',
        t.assignedTo || 'N/A'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129] }
    });
  }

  // Orders
  const jobOrders = orders.filter(o => o.jobId === job._id);
  if (jobOrders.length > 0) {
    if (doc.lastAutoTable.finalY > 200) doc.addPage();
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    const yPos = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 20;
    doc.text('Orders', 15, yPos);

    doc.autoTable({
      startY: yPos + 5,
      head: [['Item', 'Quantity', 'Status', 'Supplier', 'Expected Delivery']],
      body: jobOrders.map(o => [
        o.item,
        `${o.quantity} ${o.unit}`,
        o.status,
        o.supplier || 'N/A',
        o.expectedDelivery || 'N/A'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [245, 158, 11] }
    });
  }

  // Daily Logs
  const jobLogs = logs.filter(l => l.jobId === job._id).sort((a, b) => new Date(b.date) - new Date(a.date));
  if (jobLogs.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Daily Logs', 15, 20);

    let yPosition = 30;
    jobLogs.slice(0, 10).forEach((log, index) => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`${format(new Date(log.date), 'PPP')}`, 15, yPosition);
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      
      yPosition += 7;
      doc.text(`Weather: ${log.weather || 'N/A'} | Temp: ${log.temperature || 'N/A'}°F | Hours: ${log.hoursWorked || 0}`, 15, yPosition);
      
      if (log.notes) {
        yPosition += 7;
        const splitNotes = doc.splitTextToSize(`Notes: ${log.notes}`, pageWidth - 30);
        doc.text(splitNotes, 15, yPosition);
        yPosition += splitNotes.length * 5;
      }

      if (log.safetyObservations) {
        yPosition += 5;
        const splitSafety = doc.splitTextToSize(`Safety: ${log.safetyObservations}`, pageWidth - 30);
        doc.text(splitSafety, 15, yPosition);
        yPosition += splitSafety.length * 5;
      }

      yPosition += 10;
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount} | Generated by SiteMaster Diary | github.com/dcljlong`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
};

export const generateFullReport = (jobs, logs, tasks, orders, tools, inventory, crew, timeEntries, settings) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title Page
  if (settings?.companyLogo) {
    try {
      doc.addImage(settings.companyLogo, 'PNG', pageWidth / 2 - 25, 30, 50, 50);
    } catch (e) {
      console.log('Could not add logo');
    }
  }

  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(settings?.companyName || 'SiteMaster Diary', pageWidth / 2, 100, { align: 'center' });

  doc.setFontSize(18);
  doc.text('Complete Project Report', pageWidth / 2, 115, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${format(new Date(), 'PPpp')}`, pageWidth / 2, 130, { align: 'center' });
  doc.text(`Total Jobs: ${jobs.length}`, pageWidth / 2, 140, { align: 'center' });

  // Summary Page
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 15, 20);

  const totalHours = timeEntries.reduce((sum, te) => sum + (te.hours || 0), 0);
  const avgProgress = jobs.length > 0 
    ? Math.round(jobs.reduce((sum, j) => sum + (j.progress || 0), 0) / jobs.length) 
    : 0;
  const completedTasks = tasks.filter(t => t.status === 'completed').length;
  const pendingOrders = orders.filter(o => o.status === 'pending').length;

  doc.autoTable({
    startY: 30,
    head: [['Metric', 'Value']],
    body: [
      ['Total Jobs', jobs.length],
      ['Active Jobs', jobs.filter(j => j.status === 'active' || !j.status).length],
      ['Average Progress', `${avgProgress}%`],
      ['Total Hours Logged', `${totalHours.toFixed(1)} hours`],
      ['Total Tasks', tasks.length],
      ['Completed Tasks', completedTasks],
      ['Pending Orders', pendingOrders],
      ['Tools in Inventory', tools.length],
      ['Crew Members', crew.length]
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] }
  });

  // Jobs Overview
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Jobs Overview', 15, 20);

  doc.autoTable({
    startY: 30,
    head: [['Name', 'Address', 'Status', 'Progress', 'Start', 'End']],
    body: jobs.map(j => [
      j.name,
      j.address,
      j.status || 'Active',
      `${j.progress || 0}%`,
      j.startDate || 'N/A',
      j.expectedEndDate || 'N/A'
    ]),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] }
  });

  // All Tasks
  if (tasks.length > 0) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('All Tasks', 15, 20);

    const jobMap = {};
    jobs.forEach(j => jobMap[j._id] = j.name);

    doc.autoTable({
      startY: 30,
      head: [['Title', 'Job', 'Status', 'Priority', 'Due Date']],
      body: tasks.map(t => [
        t.title,
        jobMap[t.jobId] || 'Unknown',
        t.status,
        t.priority,
        t.dueDate || 'N/A'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129] }
    });
  }

  // Inventory
  if (inventory.length > 0) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Inventory', 15, 20);

    doc.autoTable({
      startY: 30,
      head: [['Item', 'Category', 'Quantity', 'Unit', 'Min Stock']],
      body: inventory.map(i => [
        i.name,
        i.category || 'N/A',
        i.quantity,
        i.unit || 'units',
        i.minStock || 'N/A'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [139, 92, 246] }
    });
  }

  // Crew List
  if (crew.length > 0) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Crew List', 15, 20);

    doc.autoTable({
      startY: 30,
      head: [['Name', 'Role', 'Phone', 'Email', 'Emergency Contact']],
      body: crew.map(c => [
        c.name,
        c.role || 'N/A',
        c.phone || 'N/A',
        c.email || 'N/A',
        c.emergencyContact || 'N/A'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [245, 158, 11] }
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount} | Generated by SiteMaster Diary | github.com/dcljlong`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
};

export const downloadPDF = (doc, filename) => {
  doc.save(filename);
};